#
# Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
{{- include "oracle-db-labels" . |indent 2}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      terminationGracePeriodSeconds: 60
   {{- if .Values.imagePullSecrets}}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
    {{- end }}
      securityContext:
        runAsUser: 54321
        fsGroup: 54321
    {{- if .Values.availabilityDomain }}
      nodeSelector:
        failure-domain.beta.kubernetes.io/zone: "{{ .Values.availabilityDomain }}"
    {{- end }}
      containers:
        - name: {{ template "fullname" . }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.imagePullPolicy | quote }}
          terminationMessagePath: /tmp/docker-term-log
          ports:
            - containerPort: 1521
            - containerPort: 5500
          readinessProbe:
            exec:
              command: [ '/bin/sh', '-c', '$ORACLE_BASE/checkDBLockStatus.sh' ]
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 30
          volumeMounts:
            - mountPath: /opt/oracle/oradata
              name: datamount
{{- include "oracle-db-env" . | indent 10 }}
      volumes:
        - name: datamount
          persistentVolumeClaim:
            claimName: {{ template "fullname" . }}

